### ISSUE TITLE
Add datapackage.json support to Tabular Data Viewer with a dropdown of listed data sources to load and view

### ISSUE THREAD

**Issue by RandomFractals** [RandomFractals/tabular-data-viewer#81]
This is the last remaining feature we planned for adopting frictionless data standards in #15

See `datapackage.json` specs: https://specs.frictionlessdata.io/data-package/

And https://specs.frictionlessdata.io/data-resource/#introduction

**Comment by peterdesmet** [comment]
Cool! Being able to explore a dataset from a `datapackage.json` file (only) in Visual Studio Code would be a feature I'd likely use. If you need examples of large data packages, let me know.

**Comment by RandomFractals** [comment]
Great! I think your camtrap example dataset could be a good test bed for it: https://github.com/tdwg/camtrap-dp/tree/main/example

Remote data loading will be added in #53 & I jotted some notes from our table schema naming discussion in #84.

**Comment by RandomFractals** [comment]
Created simple Observable JS notebook to explore some of the public `datapackage.json` sources published on DataHub:

https://observablehq.com/@randomfractals/data-package

**Comment by RandomFractals** [comment]
Closing this since new public Data Packages picker added in #102 provides over 750 data packages to explore from github, and there is also new `List Data Resources` context menu in editor titlebar to view tabular data sources and table views from open `datapackage.json` files (see #104).
